"""Audio / video transcription source loading with mock-first provider support.

Design constraints:
- Mock provider is default and always works without external dependencies.
- Disabled provider returns empty text + warning.
- API provider is stubbed for future use; missing config falls back to mock.
- No ffmpeg dependency.
- No local large-model dependency.
- No raw media bytes or absolute paths in metadata.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from pathlib import Path
from typing import Literal, Protocol

from app.core.config import get_settings
from app.rag.source_models import SourceDescriptor, SourceLoadResult

logger = logging.getLogger(__name__)

AUDIO_EXTENSIONS = {".mp3", ".wav", ".m4a", ".aac", ".flac", ".ogg", ".webm"}
VIDEO_EXTENSIONS = {".mp4", ".mov", ".mkv", ".webm"}
MEDIA_EXTENSIONS = AUDIO_EXTENSIONS | VIDEO_EXTENSIONS
_DEFAULT_MAX_CHARS = 30000


@dataclass(frozen=True)
class TranscriptSegment:
    """One transcript segment with optional timing."""

    text: str
    start_seconds: float | None = None
    end_seconds: float | None = None


@dataclass(frozen=True)
class MediaTranscriptResult:
    """Normalized transcription output for media-to-text ingest."""

    text: str
    provider: str
    confidence: float | None = None
    duration_seconds: float | None = None
    segments: tuple[TranscriptSegment, ...] = ()
    warnings: tuple[str, ...] = ()


class MediaTranscriptionClient(Protocol):
    """Small media transcription client contract used by MediaSourceLoader."""

    def transcribe(
        self,
        path: Path,
        media_type: Literal["audio", "video"],
    ) -> MediaTranscriptResult:
        """Transcribe a media file into text."""


@dataclass(frozen=True)
class MockMediaTranscriptionClient:
    """Deterministic mock transcription fallback."""

    text: str | None = None

    def transcribe(
        self,
        path: Path,
        media_type: Literal["audio", "video"],
    ) -> MediaTranscriptResult:
        if self.text is not None:
            return MediaTranscriptResult(
                text=self.text,
                provider="mock",
                warnings=("transcript_mock_fallback",),
            )
        if media_type == "audio":
            placeholder = (
                "[Audio Transcript - Mock Provider]\n"
                "This is a placeholder transcript generated by MindDock mock media transcription.\n"
                "No real audio understanding was performed."
            )
        else:
            placeholder = (
                "[Video Transcript - Mock Provider]\n"
                "This is a placeholder transcript generated by MindDock mock media transcription.\n"
                "No real video or frame understanding was performed."
            )
        return MediaTranscriptResult(
            text=placeholder,
            provider="mock",
            warnings=("transcript_mock_fallback",),
        )


@dataclass(frozen=True)
class DisabledMediaTranscriptionClient:
    """Transcription client used when media transcription is explicitly disabled."""

    def transcribe(
        self,
        path: Path,
        media_type: Literal["audio", "video"],
    ) -> MediaTranscriptResult:
        return MediaTranscriptResult(
            text="",
            provider="disabled",
            warnings=("transcript_disabled", "transcript_empty"),
        )


@dataclass(frozen=True)
class OptionalApiMediaTranscriptionClient:
    """Optional API provider with lazy imports and mock fallback when unconfigured."""

    fallback: MediaTranscriptionClient = MockMediaTranscriptionClient()

    def transcribe(
        self,
        path: Path,
        media_type: Literal["audio", "video"],
    ) -> MediaTranscriptResult:
        settings = get_settings()
        api_key = getattr(settings, "media_transcript_api_key", "") or ""
        api_base_url = getattr(settings, "media_transcript_api_base_url", "") or ""
        if not api_key or not api_base_url:
            logger.warning(
                "Media API provider selected but not configured (missing api_key or base_url). "
                "Falling back to mock for %s",
                path.name,
            )
            fallback_result = self.fallback.transcribe(path, media_type)
            return MediaTranscriptResult(
                text=fallback_result.text,
                provider="mock",
                warnings=_dedupe(("transcript_api_unconfigured", *fallback_result.warnings)),
            )
        # Future: real API call goes here. For P0, stub with fallback.
        fallback_result = self.fallback.transcribe(path, media_type)
        return MediaTranscriptResult(
            text=fallback_result.text,
            provider="mock",
            warnings=_dedupe(("transcript_api_stub_p0", *fallback_result.warnings)),
        )


@dataclass(frozen=True)
class MediaSourceLoader:
    """Load audio/video files by transcribing into the normal RAG text path."""

    transcription_client: MediaTranscriptionClient | None = None
    max_chars: int | None = None
    source_type: str = "file"

    def supports(self, descriptor: SourceDescriptor) -> bool:
        return (
            descriptor.source_type == "file"
            and descriptor.local_path is not None
            and descriptor.local_path.suffix.lower() in MEDIA_EXTENSIONS
        )

    def load(self, descriptor: SourceDescriptor) -> SourceLoadResult:
        path = descriptor.local_path
        if path is None:
            raise ValueError("media source requires local_path")
        suffix = path.suffix.lower()
        if suffix not in MEDIA_EXTENSIONS:
            raise ValueError(f"Unsupported media extension: {suffix}")

        media_type: Literal["audio", "video"]
        if suffix == ".webm":
            media_type = "video"
        elif suffix in AUDIO_EXTENSIONS:
            media_type = "audio"
        elif suffix in VIDEO_EXTENSIONS:
            media_type = "video"
        else:
            media_type = "video"

        client = self.transcription_client or build_media_transcription_client()
        result = client.transcribe(path, media_type)
        max_chars = self.max_chars if self.max_chars is not None else _settings_max_chars()
        text = result.text.strip()
        warnings = list(result.warnings)
        if max_chars > 0 and len(text) > max_chars:
            text = text[:max_chars].rstrip()
            warnings.append("transcript_text_truncated")
        if not text:
            warnings.append("transcript_empty")

        metadata: dict[str, str] = {
            "source_media": media_type,
            "source_kind": f"{media_type}_file",
            "loader_name": f"{media_type}.transcribe",
            "transcript_provider": result.provider,
            "retrieval_basis": "transcript_text",
            "media_filename": path.name,
        }
        if result.duration_seconds is not None:
            metadata["transcript_duration_seconds"] = f"{result.duration_seconds:.2f}"
        if result.segments:
            metadata["transcript_segment_count"] = str(len(result.segments))
        if suffix == ".webm":
            warnings.append("webm_media_type_assumed_video")

        return SourceLoadResult(
            descriptor=descriptor,
            title=path.stem,
            text=text,
            metadata=metadata,
            warnings=_dedupe(tuple(warnings)),
        )


def build_media_transcription_client() -> MediaTranscriptionClient:
    """Build a transcription client based on runtime settings."""
    settings = get_settings()
    if not getattr(settings, "media_transcript_enabled", True):
        return DisabledMediaTranscriptionClient()
    provider = str(getattr(settings, "media_transcript_provider", "mock") or "mock").strip().lower()
    if provider == "api":
        return OptionalApiMediaTranscriptionClient()
    if provider == "disabled":
        return DisabledMediaTranscriptionClient()
    return MockMediaTranscriptionClient()


def _settings_max_chars() -> int:
    return int(getattr(get_settings(), "media_transcript_max_chars", _DEFAULT_MAX_CHARS) or _DEFAULT_MAX_CHARS)


def _dedupe(warnings: tuple[str, ...]) -> tuple[str, ...]:
    return tuple(dict.fromkeys(w for w in warnings if w))
