"""Audio / video transcription source loading with mock-first provider support.

Design constraints:
- Mock provider is default and always works without external dependencies.
- Disabled provider returns empty text + warning.
- API provider calls an OpenAI-style audio transcription endpoint; missing config or errors fall back to mock.
- No ffmpeg dependency.
- No local large-model dependency.
- No raw media bytes or absolute paths in metadata.
"""

from __future__ import annotations

import json as _json
import logging
import mimetypes
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Literal, Protocol

import httpx

from app.core.config import get_settings
from app.rag.source_models import SourceDescriptor, SourceLoadResult

_LOCAL_DEV_KEY = "local-dev-key"

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class ResolvedMediaTranscriptConfig:
    """Resolved media transcript configuration with UI override > env > default priority."""

    enabled: bool
    provider: str
    api_key: str
    base_url: str
    model: str
    timeout_seconds: float
    config_source: str

AUDIO_EXTENSIONS = {".mp3", ".wav", ".m4a", ".aac", ".flac", ".ogg", ".webm"}
VIDEO_EXTENSIONS = {".mp4", ".mov", ".mkv", ".webm"}
MEDIA_EXTENSIONS = AUDIO_EXTENSIONS | VIDEO_EXTENSIONS
_DEFAULT_MAX_CHARS = 30000
SIDECAR_TRANSCRIPT_SUFFIXES = (
    ".transcript.md",
    ".transcript.txt",
    ".txt",
    ".vtt",
    ".srt",
)


@dataclass(frozen=True)
class TranscriptSegment:
    """One transcript segment with optional timing."""

    text: str
    start_seconds: float | None = None
    end_seconds: float | None = None


@dataclass(frozen=True)
class MediaTranscriptResult:
    """Normalized transcription output for media-to-text ingest."""

    text: str
    provider: str
    confidence: float | None = None
    duration_seconds: float | None = None
    segments: tuple[TranscriptSegment, ...] = ()
    warnings: tuple[str, ...] = ()
    sidecar_filename: str | None = None
    sidecar_format: str | None = None


class MediaTranscriptionClient(Protocol):
    """Small media transcription client contract used by MediaSourceLoader."""

    def transcribe(
        self,
        path: Path,
        media_type: Literal["audio", "video"],
    ) -> MediaTranscriptResult:
        """Transcribe a media file into text."""


@dataclass(frozen=True)
class MockMediaTranscriptionClient:
    """Deterministic mock transcription fallback."""

    text: str | None = None

    def transcribe(
        self,
        path: Path,
        media_type: Literal["audio", "video"],
    ) -> MediaTranscriptResult:
        if self.text is not None:
            return MediaTranscriptResult(
                text=self.text,
                provider="mock",
                warnings=("transcript_mock_fallback",),
            )
        if media_type == "audio":
            placeholder = (
                "[Audio Transcript - Mock Provider]\n"
                "This is a placeholder transcript generated by MindDock mock media transcription.\n"
                "No real audio understanding was performed."
            )
        else:
            placeholder = (
                "[Video Transcript - Mock Provider]\n"
                "This is a placeholder transcript generated by MindDock mock media transcription.\n"
                "No real video or frame understanding was performed."
            )
        return MediaTranscriptResult(
            text=placeholder,
            provider="mock",
            warnings=("transcript_mock_fallback",),
        )


@dataclass(frozen=True)
class DisabledMediaTranscriptionClient:
    """Transcription client used when media transcription is explicitly disabled."""

    def transcribe(
        self,
        path: Path,
        media_type: Literal["audio", "video"],
    ) -> MediaTranscriptResult:
        return MediaTranscriptResult(
            text="",
            provider="disabled",
            warnings=("transcript_disabled", "transcript_empty"),
        )


@dataclass(frozen=True)
class OptionalApiMediaTranscriptionClient:
    """Optional API provider that calls an OpenAI-style audio transcription endpoint.

    When configuration is missing, HTTP/network errors occur, or the API returns
    empty text, this client falls back to mock and records appropriate warnings
    without exposing the API key.
    """

    fallback: MediaTranscriptionClient = MockMediaTranscriptionClient()
    api_key: str = ""
    api_base_url: str = ""
    model: str = ""
    timeout_seconds: float = 0.0

    def transcribe(
        self,
        path: Path,
        media_type: Literal["audio", "video"],
    ) -> MediaTranscriptResult:
        api_key = self.api_key.strip()
        api_base_url = self.api_base_url.strip()
        if not api_key or not api_base_url:
            logger.warning(
                "Media API provider selected but not configured (missing api_key or base_url). "
                "Falling back to mock for %s",
                path.name,
            )
            fallback_result = self.fallback.transcribe(path, media_type)
            return MediaTranscriptResult(
                text=fallback_result.text,
                provider="mock",
                warnings=_dedupe(("transcript_api_unconfigured", "transcript_mock_fallback", *fallback_result.warnings)),
            )

        model = self.model.strip() or "whisper-1"
        timeout = self.timeout_seconds if self.timeout_seconds > 0 else 60.0
        endpoint = _build_transcription_endpoint(api_base_url)

        try:
            content_type, _ = mimetypes.guess_type(str(path))
            content_type = content_type or "application/octet-stream"

            with path.open("rb") as file_obj:
                files = {"file": (path.name, file_obj, content_type)}
                data = {"model": model}
                response = httpx.post(
                    endpoint,
                    headers={"Authorization": f"Bearer {api_key}"},
                    data=data,
                    files=files,
                    timeout=timeout,
                )
                response.raise_for_status()
                payload = response.json()
                text = (payload.get("text", "") or "").strip()
        except httpx.HTTPStatusError:
            logger.warning("ASR API returned HTTP error for %s", path.name)
            return _api_fallback(self.fallback, path, media_type, "transcript_api_http_error")
        except httpx.TimeoutException:
            logger.warning("ASR API request timed out for %s", path.name)
            return _api_fallback(self.fallback, path, media_type, "transcript_api_timeout")
        except (httpx.NetworkError, httpx.ConnectError):
            logger.warning("ASR API network error for %s", path.name)
            return _api_fallback(self.fallback, path, media_type, "transcript_api_network_error")
        except (_json.JSONDecodeError, AttributeError):
            logger.warning("ASR API returned unparseable response for %s", path.name)
            return _api_fallback(self.fallback, path, media_type, "transcript_api_parse_error")

        if not text:
            logger.warning("ASR API returned empty transcript for %s", path.name)
            return _api_fallback(self.fallback, path, media_type, "transcript_api_empty")

        return MediaTranscriptResult(
            text=text,
            provider="api",
            segments=tuple(TranscriptSegment(line) for line in text.splitlines() if line.strip()),
        )


def _api_fallback(
    fallback: MediaTranscriptionClient,
    path: Path,
    media_type: Literal["audio", "video"],
    reason: str,
) -> MediaTranscriptResult:
    fb = fallback.transcribe(path, media_type)
    return MediaTranscriptResult(
        text=fb.text,
        provider="mock",
        warnings=_dedupe((reason, "transcript_mock_fallback", *fb.warnings)),
    )


def _build_transcription_endpoint(base_url: str) -> str:
    base = base_url.rstrip("/")
    if base.endswith("/audio/transcriptions"):
        return base
    return f"{base}/audio/transcriptions"


@dataclass(frozen=True)
class MediaSourceLoader:
    """Load audio/video files by transcribing into the normal RAG text path."""

    transcription_client: MediaTranscriptionClient | None = None
    max_chars: int | None = None
    source_type: str = "file"

    def supports(self, descriptor: SourceDescriptor) -> bool:
        return (
            descriptor.source_type == "file"
            and descriptor.local_path is not None
            and descriptor.local_path.suffix.lower() in MEDIA_EXTENSIONS
        )

    def load(self, descriptor: SourceDescriptor) -> SourceLoadResult:
        path = descriptor.local_path
        if path is None:
            raise ValueError("media source requires local_path")
        suffix = path.suffix.lower()
        if suffix not in MEDIA_EXTENSIONS:
            raise ValueError(f"Unsupported media extension: {suffix}")

        media_type: Literal["audio", "video"]
        if suffix == ".webm":
            media_type = "video"
        elif suffix in AUDIO_EXTENSIONS:
            media_type = "audio"
        elif suffix in VIDEO_EXTENSIONS:
            media_type = "video"
        else:
            media_type = "video"

        result = _load_sidecar_transcript(path)
        if result is None:
            client = self.transcription_client or build_media_transcription_client()
            result = client.transcribe(path, media_type)
        max_chars = self.max_chars if self.max_chars is not None else _settings_max_chars()
        text = result.text.strip()
        warnings = list(result.warnings)
        if max_chars > 0 and len(text) > max_chars:
            text = text[:max_chars].rstrip()
            warnings.append("transcript_text_truncated")
        if not text:
            warnings.append("transcript_empty")

        metadata: dict[str, str] = {
            "source_media": media_type,
            "source_kind": f"{media_type}_file",
            "loader_name": f"{media_type}.transcribe",
            "transcript_provider": result.provider,
            "retrieval_basis": "transcript_text",
            "media_filename": path.name,
        }
        sidecar_metadata = _sidecar_metadata(result)
        metadata.update(sidecar_metadata)
        if result.duration_seconds is not None:
            metadata["transcript_duration_seconds"] = f"{result.duration_seconds:.2f}"
        if result.segments:
            metadata["transcript_segment_count"] = str(len(result.segments))
        if suffix == ".webm":
            warnings.append("webm_media_type_assumed_video")

        return SourceLoadResult(
            descriptor=descriptor,
            title=path.stem,
            text=text,
            metadata=metadata,
            warnings=_dedupe(tuple(warnings)),
        )


def _resolve_media_transcript_runtime_config() -> ResolvedMediaTranscriptConfig:
    """Resolve media transcript config with UI active config > settings > env > default priority."""
    from app.runtime.media_transcript_active_config import (
        CONFIG_FILE,
        get_active_media_transcript_config,
        get_effective_media_transcript_api_key,
        get_effective_media_transcript_base_url,
        get_effective_media_transcript_config_source,
        get_effective_media_transcript_model,
        get_effective_media_transcript_provider,
        get_effective_media_transcript_timeout,
        get_effective_local_asr_server_path,
        get_effective_local_asr_host,
        get_effective_local_asr_port,
        get_effective_local_asr_auto_start,
        get_effective_local_asr_timeout_seconds,
    )

    settings = get_settings()
    active = get_active_media_transcript_config()

    if active.enabled:
        enabled = True
    elif not CONFIG_FILE.exists():
        # No active config on disk -- fall back to settings
        enabled = bool(getattr(settings, "media_transcript_enabled", True))
    else:
        # Active config file exists but is disabled -- respect the UI choice
        enabled = False

    return ResolvedMediaTranscriptConfig(
        enabled=enabled,
        provider=get_effective_media_transcript_provider(active, settings),
        api_key=get_effective_media_transcript_api_key(active, settings),
        base_url=get_effective_media_transcript_base_url(active, settings),
        model=get_effective_media_transcript_model(active, settings),
        timeout_seconds=get_effective_media_transcript_timeout(active, settings),
        config_source=get_effective_media_transcript_config_source(active, settings),
        local_asr_server_path=get_effective_local_asr_server_path(active, settings),
        local_asr_host=get_effective_local_asr_host(active, settings),
        local_asr_port=get_effective_local_asr_port(active, settings),
        local_asr_auto_start=get_effective_local_asr_auto_start(active, settings),
        local_asr_timeout_seconds=get_effective_local_asr_timeout_seconds(active, settings),
    )


def build_media_transcription_client() -> MediaTranscriptionClient:
    """Build a transcription client based on resolved runtime config (UI override > env > default)."""
    resolved = _resolve_media_transcript_runtime_config()
    if not resolved.enabled:
        return DisabledMediaTranscriptionClient()
    if resolved.provider == "api":
        return OptionalApiMediaTranscriptionClient(
            api_key=resolved.api_key,
            api_base_url=resolved.base_url,
            model=resolved.model,
            timeout_seconds=resolved.timeout_seconds,
        )
    if resolved.provider == "local":
        try:
            from app.runtime.local_asr_bootstrap import ensure_local_asr_if_enabled

            result = ensure_local_asr_if_enabled(
                provider="local",
                server_path=resolved.local_asr_server_path,
                host=resolved.local_asr_host,
                port=resolved.local_asr_port,
                auto_start=resolved.local_asr_auto_start,
                timeout_seconds=resolved.local_asr_timeout_seconds,
            )
            if result.status in ("already_running", "started"):
                return OptionalApiMediaTranscriptionClient(
                    api_key=_LOCAL_DEV_KEY,
                    api_base_url=result.base_url,
                    model=resolved.model,
                    timeout_seconds=resolved.local_asr_timeout_seconds,
                )
            logger.warning("Local ASR bootstrap failed: %s", result.message)
        except Exception:
            logger.exception("Local ASR bootstrap error.")
        # Fallback to mock on any bootstrap failure
        return MockMediaTranscriptionClient()
    if resolved.provider == "disabled":
        return DisabledMediaTranscriptionClient()
    return MockMediaTranscriptionClient()


def _load_sidecar_transcript(path: Path) -> MediaTranscriptResult | None:
    sidecar_path = _find_sidecar_transcript(path)
    if sidecar_path is None:
        return None

    raw_text = sidecar_path.read_text(encoding="utf-8", errors="ignore")
    sidecar_format = _sidecar_format(sidecar_path)
    text = _normalize_sidecar_transcript(raw_text, sidecar_format)
    segments = tuple(TranscriptSegment(line) for line in text.splitlines() if line.strip())
    warnings: tuple[str, ...] = () if text else ("transcript_sidecar_empty",)
    return MediaTranscriptResult(
        text=text,
        provider="sidecar",
        segments=segments,
        warnings=warnings,
        sidecar_filename=sidecar_path.name,
        sidecar_format=sidecar_format,
    )


def _find_sidecar_transcript(path: Path) -> Path | None:
    for suffix in SIDECAR_TRANSCRIPT_SUFFIXES:
        candidate = path.with_name(f"{path.stem}{suffix}")
        if candidate.is_file():
            return candidate
    return None


def is_media_sidecar_transcript(path: Path) -> bool:
    """Return whether path is a transcript sidecar for a sibling media file."""

    sidecar_stem = _sidecar_media_stem(path)
    if sidecar_stem is None:
        return False
    return any(path.with_name(f"{sidecar_stem}{extension}").is_file() for extension in MEDIA_EXTENSIONS)


def _sidecar_media_stem(path: Path) -> str | None:
    name = path.name.lower()
    if name.endswith(".transcript.md"):
        return path.name[: -len(".transcript.md")]
    if name.endswith(".transcript.txt"):
        return path.name[: -len(".transcript.txt")]
    if path.suffix.lower() in {".txt", ".vtt", ".srt"}:
        return path.stem
    return None


def _sidecar_format(path: Path) -> str:
    name = path.name.lower()
    if name.endswith(".transcript.md"):
        return "md"
    if name.endswith(".transcript.txt"):
        return "txt"
    suffix = path.suffix.lower().lstrip(".")
    return suffix or "txt"


def _sidecar_metadata(result: MediaTranscriptResult) -> dict[str, str]:
    if result.provider != "sidecar":
        return {}
    metadata: dict[str, str] = {}
    if result.sidecar_filename:
        metadata["transcript_sidecar_filename"] = result.sidecar_filename
    if result.sidecar_format:
        metadata["transcript_sidecar_format"] = result.sidecar_format
    return metadata


def _normalize_sidecar_transcript(raw_text: str, sidecar_format: str) -> str:
    if sidecar_format == "srt":
        return _strip_timed_transcript(raw_text, skip_webvtt_header=False)
    if sidecar_format == "vtt":
        return _strip_timed_transcript(raw_text, skip_webvtt_header=True)
    return "\n".join(line.strip() for line in raw_text.splitlines() if line.strip()).strip()


def _strip_timed_transcript(raw_text: str, *, skip_webvtt_header: bool) -> str:
    lines: list[str] = []
    for raw_line in raw_text.splitlines():
        line = raw_line.strip().lstrip("\ufeff")
        if not line:
            continue
        if skip_webvtt_header and line.upper() == "WEBVTT":
            continue
        if line.isdigit():
            continue
        if "-->" in line:
            continue
        if re.match(r"^(NOTE|STYLE|REGION)(\s|$)", line, flags=re.IGNORECASE):
            continue
        lines.append(line)
    return "\n".join(lines).strip()


def _settings_max_chars() -> int:
    return int(getattr(get_settings(), "media_transcript_max_chars", _DEFAULT_MAX_CHARS) or _DEFAULT_MAX_CHARS)


def _dedupe(warnings: tuple[str, ...]) -> tuple[str, ...]:
    return tuple(dict.fromkeys(w for w in warnings if w))
